[package]
name = "tic-tac-toers"
version = "0.1.0"
authors = ["Davi William Moraes Suga <daviciencia1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.4"